#################################################
# Tasks for Ophidia server SSL certs
- name: RedHat | Check root SSL cert
  stat: path=/usr/local/ophidia/oph-server/etc/cert/cacert.pem
  register: cacert

- name: RedHat | Check server SSL cert
  stat: path=/usr/local/ophidia/oph-server/etc/cert/myserver.pem
  register: myserver

- name: RedHat | Creating root SSL cert
  command: >
    openssl req
      -newkey rsa:1024
      -passout pass:{{ cert_passwd }}
      -subj "/"
      -sha1
      -keyout rootkey.pem
      -out rootreq.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    creates: /usr/local/ophidia/oph-server/etc/cert/rootreq.pem
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | Sign root SSL cert
  command: >
    openssl x509
      -req
      -in rootreq.pem
      -passin pass:{{ cert_passwd }}
      -sha1
      -extensions v3_ca
      -signkey rootkey.pem
      -out rootcert.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    creates: /usr/local/ophidia/oph-server/etc/cert/rootcert.pem
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | merge cert and key of root cert
  shell: cat rootcert.pem rootkey.pem > cacert.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | Creating server SSL cert
  command: >
    openssl req
      -newkey rsa:1024
      -passout pass:{{ cert_passwd }}
      -subj "/"
      -sha1
      -keyout serverkey.pem
      -out serverreq.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    creates: /usr/local/ophidia/oph-server/etc/cert/serverreq.pem
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | Sign server SSL cert
  command: >
    openssl x509
      -req
      -in serverreq.pem
      -passin pass:{{ cert_passwd }}
      -sha1
      -extensions usr_cert
      -CA cacert.pem
      -CAkey cacert.pem
      -CAcreateserial
      -out servercert.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    creates: /usr/local/ophidia/oph-server/etc/cert/servercert.pem
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | merge cert and key of server cert
  shell: cat servercert.pem serverkey.pem rootcert.pem > myserver.pem
  args:
    chdir: /usr/local/ophidia/oph-server/etc/cert
    executable: /bin/bash
  become: yes
  become_user: "{{ oph_user }}"
  when: cacert.stat.exists == False or myserver.stat.exists == False

- name: RedHat | Remove intermediate certs
  file: path={{ item }} state=absent
  with_items:
    - /usr/local/ophidia/oph-server/etc/cert/rootcert.pem
    - /usr/local/ophidia/oph-server/etc/cert/rootkey.pem
    - /usr/local/ophidia/oph-server/etc/cert/rootreq.pem
    - /usr/local/ophidia/oph-server/etc/cert/servercert.pem
    - /usr/local/ophidia/oph-server/etc/cert/serverkey.pem
    - /usr/local/ophidia/oph-server/etc/cert/serverreq.pem
    - /usr/local/ophidia/oph-server/etc/cert/cacert.srl

